/**
 * Маппинг API-endpoint модели → имя модели в AccessRight (PascalCase).
 * Используется для проверки прав на фронтенде.
 */
export const ENDPOINT_TO_MODEL: Record<string, string> = {
	organizations: "Organization",
	counterparties: "Counterparty",
	contracts: "Contract",
	"contract-files": "AttachedFile",
	contractfiles: "AttachedFile",
	contacts: "Contact",
	contactpersons: "ContactPerson",
	bankaccounts: "BankAccount",
	activityhistories: "ActivityHistory",
	todos: "Todo",
	notifications: "Notification",
	warehouses: "Warehouse",
	sales: "Sale",
	purchases: "Purchase",
	"outgoing-invoices": "OutgoingInvoice",
	"incoming-invoices": "IncomingInvoice",
	"payment-invoices": "PaymentInvoice",
	"scheduled-tasks": "ScheduledTask",
	"inventory-transfers": "InventoryTransfer",
	"commercial-offers": "CommercialOffer",
	"sales-orders": "SalesOrder",
	"reservations": "Reservation",
	"purchase-orders": "PurchaseOrder",
	"bank-statements": "BankStatement",
	"cash-receipt-orders": "CashReceiptOrder",
	"cash-expense-orders": "CashExpenseOrder",
	brands: "Brand",
	products: "Product",
	saleitems: "SaleItem",
	employees: "Employee",
	positions: "Position",
	"employee-histories": "EmployeeHistory",
	"access-rights": "AccessRight",
	currencies: "Currency",
	"chart-of-accounts": "ChartOfAccount",
	"subkonto-types": "SubkontoType",
	accounting: "AccountingEntry",
	users: "User",
	files: "AttachedFile",
	todofiles: "Todo",
};
