/**
 * Маппинг API-endpoint модели → имя модели в UserAccessRight (PascalCase).
 * Используется для проверки прав на фронтенде.
 */
export const ENDPOINT_TO_MODEL: Record<string, string> = {
	organizations: "Organization",
	counterparties: "Counterparty",
	contracts: "Contract",
	"contract-files": "AttachedFile",
	contractfiles: "AttachedFile",
	contacts: "Contact",
	contactpersons: "ContactPerson",
	bankaccounts: "BankAccount",
	activityhistories: "ActivityHistory",
	pipeactivities: "ActivityHistory",
	todos: "Todo",
	notifications: "Notification",
	warehouses: "Warehouse",
	sales: "Sale",
	purchases: "Purchase",
	"outgoing-invoices": "OutgoingInvoice",
	"incoming-invoices": "IncomingInvoice",
	"payment-invoices": "PaymentInvoice",
	"scheduled-tasks": "ScheduledTask",
	"inventory-transfers": "InventoryTransfer",
	"commercial-offers": "CommercialOffer",
	"sales-orders": "SalesOrder",
	"reservations": "Reservation",
	"purchase-orders": "PurchaseOrder",
	importdeclarations: "ImportDeclaration",
	writeoffs: "WriteOff",
	goodsreceipts: "GoodsReceipt",
	serialnumbers: "SerialNumber",
	stockcounts: "StockCount",
	"bank-statements": "BankStatement",
	"month-closes": "MonthClose",
	"fiscal-receipts": "FiscalReceipt",
	edo: "EdoDocument",
	"cash-receipt-orders": "CashReceiptOrder",
	"cash-expense-orders": "CashExpenseOrder",
	brands: "Brand",
	products: "Product",
	saleitems: "SaleItem",
	employees: "Employee",
	positions: "Position",
	"employee-histories": "EmployeeHistory",
	"user-access-rights": "UserAccessRight",
	currencies: "Currency",
	"chart-of-accounts": "ChartOfAccount",
	"subkonto-types": "SubkontoType",
	accounting: "AccountingEntry",
	users: "User",
	files: "AttachedFile",
	todofiles: "Todo",
};
