/**
 * XlsxReportPane — report container backed by an XLSX template.
 *
 * Workflow:
 *   1. Fetch XLSX template from `templateUrl` (or use `template` ArrayBuffer directly).
 *   2. Fill template placeholders with `data` via fillXlsxTemplate().
 *   3. Render the first sheet (or `sheetName`) as HTML via XLSX.utils.sheet_to_html().
 *   4. Display inside ReportPane (dark viewport + A4 sheet), passing filled workbook
 *      for XLSX/XLS export.
 *
 * Placeholder syntax:
 *   {{key}}           — scalar value from data
 *   {{#sectionName}}  — start of repeating block (data[sectionName] must be an array)
 *   {{/sectionName}}  — end of repeating block
 */
import { FC, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import type { WorkBook } from "xlsx";
import { fillXlsxTemplate, type TTemplateData } from "src/utils/xlsxTemplate";
import ReportPane, { type ReportPageOrientation } from "./index";
import styles from "./XlsxSheet.module.scss";
import type { ReactNode } from "react";

// ── Types ────────────────────────────────────────────────────────────────────

export interface XlsxReportPaneProps {
  /**
   * URL of the XLSX template file.
   * The file is fetched once (on mount / when url changes) and cached in state.
   */
  templateUrl?: string;
  /**
   * Pre-loaded template as ArrayBuffer.
   * Use this instead of `templateUrl` when you manage fetching yourself.
   */
  template?: ArrayBuffer;
  /** Data to fill into the template. */
  data: TTemplateData;
  /** Sheet name to render (defaults to first sheet). */
  sheetName?: string;
  /** Filter / parameter form shown above the sheet preview. */
  form?: ReactNode;
  /** Pane uniqId — auto-provided by the MDI pane system. */
  uniqId?: string;
  /** Base filename for downloads (without extension). */
  fileBaseName?: string;
  /** Title shown in print dialog. */
  title?: string;
  /** Sheet orientation for the A4 container (default "portrait"). */
  orientation?: ReportPageOrientation;
  /** Show loading state while fetching or processing the template. */
  isLoading?: boolean;
}

// ── Component ────────────────────────────────────────────────────────────────

const XlsxReportPane: FC<XlsxReportPaneProps> = ({
  templateUrl,
  template,
  data,
  sheetName,
  form,
  uniqId,
  fileBaseName = "report",
  title,
  orientation = "portrait",
  isLoading: externalLoading = false,
}) => {
  const [rawTemplate, setRawTemplate] = useState<ArrayBuffer | null>(
    template ?? null,
  );
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [fetching, setFetching] = useState(false);

  // Fetch template from URL when templateUrl changes
  useEffect(() => {
    if (!templateUrl) return;
    let cancelled = false;
    setFetching(true);
    setFetchError(null);
    fetch(templateUrl)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.arrayBuffer();
      })
      .then(buf => {
        if (!cancelled) {
          setRawTemplate(buf);
          setFetching(false);
        }
      })
      .catch(e => {
        if (!cancelled) {
          setFetchError(String(e));
          setFetching(false);
        }
      });
    return () => { cancelled = true; };
  }, [templateUrl]);

  // Use prop template if provided (prop takes priority)
  useEffect(() => {
    if (template) setRawTemplate(template);
  }, [template]);

  // Parse and fill template whenever rawTemplate or data changes
  const filledWorkbook = useMemo<WorkBook | null>(() => {
    if (!rawTemplate) return null;
    const wb = XLSX.read(new Uint8Array(rawTemplate), { type: "array" });
    return fillXlsxTemplate(wb, data);
  }, [rawTemplate, data]);

  // Render selected sheet to HTML
  const html = useMemo<string>(() => {
    if (!filledWorkbook) return "";
    const name = sheetName && filledWorkbook.SheetNames.includes(sheetName)
      ? sheetName
      : filledWorkbook.SheetNames[0];
    if (!name) return "";
    const ws = filledWorkbook.Sheets[name];
    return XLSX.utils.sheet_to_html(ws, { id: "xlsx-preview-table", editable: false });
  }, [filledWorkbook, sheetName]);

  const isLoading = externalLoading || fetching;
  const isEmpty   = !isLoading && !fetchError && !html;

  const layout = fetchError ? (
    <div style={{ color: "#dc2626", padding: "16px", fontFamily: "sans-serif" }}>
      {fetchError}
    </div>
  ) : (
    // dangerouslySetInnerHTML is safe here: content is generated by SheetJS
    // from a controlled XLSX template, not from user/network text input.
    <div
      className={styles.XlsxSheet}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );

  return (
    <ReportPane
      uniqId={uniqId}
      form={form}
      layout={layout}
      workbook={filledWorkbook ?? undefined}
      fileBaseName={fileBaseName}
      title={title}
      orientation={orientation}
      isLoading={isLoading}
      isEmpty={isEmpty}
      sheetFit="content"
    />
  );
};

XlsxReportPane.displayName = "XlsxReportPane";
export default XlsxReportPane;
